scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: laser_sensor
    min_x: -0.5
    max_x: 0.5
    min_y: -0.5
    max_y: 0.5
    min_z: -0.5
    max_z: 0.5
